### ISSUE TITLE
Only the first page of PDFs is downladed...

### ISSUE THREAD

**Issue by alexdu** [milianw/springer_download#10]
... because the link now has also a Title attribute, and the old regex doesn't work. Here is the new regex which worked for me:

```
<a href="([^"#]+)"[^>]*>Next</a>
```

(replaced the old one on lines 148 and 158)

Thanks for a great script!

**Comment by milianw** [comment]
please send me a patch so I can include it.

**Comment by milianw** [comment]
included now, thanks
