### ISSUE TITLE
Add support for the new Springer website & fix chapter ordering

### ISSUE THREAD

**Issue by amergin** [milianw/springer_download#21]
Seems that Springer has updated their website structure and URL space, for instance a book previously located at http://www.springerlink.com/content/978-94-007-4655-8 is now being redirected to http://link.springer.com/book/10.1007/978-94-007-4655-8/page/1, causing the script not to work.

Before this change, Springer, I guess, made some changes to the old site as well since the chapter ordering in the bound pdf is incorrect (see comments in http://milianw.de/code-snippets/take-2-download-script-for-springerlinkcom-ebooks)

Would be great if these issues were fixed. This is a great tool!

**Comment by sebastianst** [comment]
When browsing the website with a browser, one can choose to go back to the old website. Then urls of the old style don't get redirected... If one could implement this choice in the script, this would be a quick fix until springer removes the old website completely

**Comment by sebastianst** [comment]
I found a workaround to use the old website, see issue #22 :)

**Comment by milianw** [comment]
applied, thanks
