### ISSUE TITLE
don't put back-matter in pdf twice

### ISSUE THREAD

**Issue by ch-aurich** [milianw/springer_download#6]
Some books I've downloaded contained the back matter after the front matter and also after the other chapters.
This patch removes the first appearance after the front matter.

<pre>
--- springer_download.py.ori    2010-09-29 00:59:40.000000000 +0100
+++ springer_download.py    2010-10-15 13:30:46.000000000 +0100
@@ -142,6 +155,9 @@
                     front_matter = True
             if re.search(r'back-matter.pdf', chapterLink) and re.search(r'&lt;a href="([^"]+)">Next&lt;/a>', page):
                 continue
+            #skip backmatter if it is in list as second chapter - will be there at the end of the book also
+            if re.search(r'back-matter.pdf', chapterLink):
+                if len(chapters)&lt;2:
+                    continue
 
             chapters.append(chapterLink)
</pre>

**Comment by milianw** [comment]
that patch doesn't make any sense, there is missing something after the if len(...) condition, no?

**Comment by milianw** [comment]
lol when I edit your comment I can see the full patch, will apply - thanks

**Comment by milianw** [comment]
stupid github does not escape &lt; as &amp;lt; ...

**Comment by milianw** [comment]
comtted
